kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
      - echo $(TZ=UTC-8 date +%Y-%m-%d" "%H:%M:%S)
      - echo -------end--line-------